<?php

/**
 * Processes variables for theme_field().
 */
function atoms_process_field(&$vars) {
  $element = $vars['element'];
  if ($element['#field_name'] == 'field_content') {

    // Simplify items:
    $items = $vars['items'];
    foreach ($items as $delta => $item) {
      $tmp_item = reset($item);
      $tmp_item = reset($tmp_item);
      $tmp_item['#atoms'] = array();
      $items[$delta] = $tmp_item;
    }

    // Reverse items to process them without recursion:
    $items = array_reverse($items, TRUE);

    // Process items:
    foreach ($items as $delta => $item) {
      if (isset($element['#items'][$delta]['treeable_parent'])) {
        $parent = $element['#items'][$delta]['treeable_parent'];
        array_unshift($items[$parent]['#atoms'], $items[$delta]);
        unset($items[$delta]);
      }
    }

    // Reverse items back:
    $items = array_reverse($items, TRUE);

    $vars['items'] = $items;
  }
}

/**
 * Preprocesses variables for entity.tpl.php.
 */
function atoms_preprocess_entity(&$vars) {
  $element = $vars['elements'];
  if ($element['#entity_type'] == 'atom') {
    $vars['classes_array'][] = 'atom-' . $element['#bundle'];
    $vars['atoms'] = array();
    if (isset($element['#atoms'])) {
      $vars['atoms'] = $element['#atoms'];
    }
  }
}

/**
 * Processes variables for entity.tpl.php.
 */
function atoms_process_entity(&$vars) {
  $element = $vars['elements'];
  if ($element['#entity_type'] == 'atom') {
    $vars['prefix'] = '<div class="' . $vars['classes'] . '">' . drupal_render($vars['title_prefix']) . drupal_render($vars['title_suffix']);
    $vars['suffix'] = '</div>';
  }
}
