<?php

/**
 * Processes variables for theme_field().
 */
function brickdown_process_field(&$vars) {
  $element = $vars['element'];
  if ($element['#field_name'] == 'field_brick') {

    // Simplify items:
    $items = $vars['items'];
    foreach ($items as $delta => $item) {
      $tmp_item = reset($item);
      $tmp_item = reset($tmp_item);
      $tmp_item['#bricks'] = array();
      $items[$delta] = $tmp_item;
    }

    // Reverse items to process them without recursion:
    $items = array_reverse($items, TRUE);

    // Process items:
    foreach ($items as $delta => $item) {
      if (isset($element['#items'][$delta]['treeable_parent'])) {
        $parent = $element['#items'][$delta]['treeable_parent'];
        array_unshift($items[$parent]['#bricks'], $items[$delta]);
        unset($items[$delta]);
      }
    }

    // Reverse items back:
    $items = array_reverse($items, TRUE);

    $vars['items'] = $items;
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function brickdown_entity_view_alter(&$build, $type) {
  if ($type == 'brick' && !isset($build['#contextual_links'])) {
    $build['#contextual_links'] = array(
      'entity' => array(
        'brick' . '/' . $build['#bundle'],
        array($build['#entity']->id),
      ),
    );
  }
}

/**
 * Preprocesses variables for entity.tpl.php.
 */
function brickdown_preprocess_entity(&$vars) {
  $element = $vars['elements'];
  if ($element['#entity_type'] == 'brick') {
    $vars['classes_array'][] = 'brick-' . $element['#bundle'];
    $vars['bricks'] = array();
    if (isset($element['#bricks'])) {
      $vars['bricks'] = $element['#bricks'];
    }
  }
}

/**
 * Processes variables for entity.tpl.php.
 */
function brickdown_process_entity(&$vars) {
  $element = $vars['elements'];
  if ($element['#entity_type'] == 'brick') {
    $vars['prefix'] = '<div class="' . $vars['classes'] . '">' . drupal_render($vars['title_prefix']) . drupal_render($vars['title_suffix']);
    $vars['suffix'] = '</div>';
  }
}
