<?php

/**
 * Implements hook_theme_registry_alter() as described here: https://www.drupal.org/node/715160.
 */
function bricks_theme_registry_alter(&$theme_registry, $module = 'bricks') {
  $theme_registry_copy = $theme_registry;
  $module_path = drupal_get_path('module', $module);
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', $module, $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  // A list of templates the module will provide templates for
  $hooks = array('entity');
  foreach ($hooks as $hook) {
    // Add the key 'theme paths' if it doesn't exist in this theme's registry
    if (!isset($theme_registry[$hook]['theme paths'])) {
      $theme_registry[$hook]['theme paths'] = array();
    }
    // Shift this module's directory to the top of the theme path list
    if (is_array($theme_registry[$hook]['theme paths'])) {
      $first_element = array_shift($theme_registry[$hook]['theme paths']);
      if ($first_element) {
        array_unshift($theme_registry[$hook]['theme paths'], $first_element, $module_path);
      }
      else {
        array_unshift($theme_registry[$hook]['theme paths'], $module_path);
      }
    }
  }
}

/**
 * Preprocesses variables for entity.tpl.php.
 */
function bricks_preprocess_entity(&$vars) {
  $element = &$vars['elements'];
  if ($element['#entity_type'] == 'brick') {
    $vars['title'] = '';
    if (!empty($vars['content']['field_title']['#items'][0]['value'])) {
      $vars['title'] = $vars['content']['field_title']['#items'][0]['value'];
      unset($vars['content']['field_title']);
    }
    $base_heading_level = isset($element['#base_heading_level']) ? $element['#base_heading_level'] : 1;
    $element['#heading_level'] = $base_heading_level + !empty($vars['title']);

    if ($element['#bundle'] == 'unit') {
      $vars['theme_hook_suggestions'][] = 'brick__unit__' . $element['#entity']->machine_name;
      if ($element['#view_mode'] == 'teaser') {
        $vars['title'] = htmlspecialchars('<' . $element['#entity']->machine_name . '>');
      }
    }

    if ($element['#bundle'] == 'molecule' && isset($vars['content']['field_content'])) {
      $vars['content']['bricks'] = _bricks_molecular_items($element['field_content'], $vars['content']['field_content']);
      unset($vars['content']['field_content']);
    }
  }
}

/**
 * Processes variables for entity.tpl.php.
 */
function bricks_process_entity(&$vars) {
  $element = &$vars['elements'];
  if ($element['#entity_type'] == 'brick') {
    $vars['prefix'] = '<div class="' . $vars['classes'] . '"' . $vars['attributes'] . '>' . drupal_render($vars['title_prefix']) . drupal_render($vars['title_suffix']);
    $vars['suffix'] = '</div>';
    $vars['heading'] = !empty($vars['title']) ? '<h' . $element['#heading_level'] . '>' . $vars['title'] . '</h' . $element['#heading_level'] . '>' : '';

    if (isset($vars['content']['bricks'])) {
      foreach ($vars['content']['bricks'] as &$brick) {
        $brick['#base_heading_level'] = $element['#heading_level'];
      }
    }
  }
}

/**
 * Helper function: converts element's items to molecualar structure.
 */
function _bricks_molecular_items($element, $items) {

  // Filter items:
  $items = array_filter($items, 'element_child', ARRAY_FILTER_USE_KEY);

  // Simplify items:
  foreach ($items as $delta => $item) {
    $item = reset($item);
    $item = reset($item);
    $item['bricks'] = array();
    $items[$delta] = $item;
  }

  // Process items in reverse order (without recursion):
  $ritems = array_reverse($items, TRUE);
  foreach ($ritems as $delta => $item) {
    if (isset($element['#items'][$delta]['treeable_parent'])) {
      $parent = $element['#items'][$delta]['treeable_parent'];
      array_unshift($items[$parent]['bricks'], $items[$delta]);
      unset($items[$delta]);
    }
  }

  return $items;
}

/**
 * Processes variables for theme_field().
 */
function bricks_molecules_process_field(&$vars) {
  $element = &$vars['element'];
  if ($element['#field_name'] == 'field_content') {
    $vars['items'] = _bricks_molecular_items($element, $vars['items']);
  }
}

/**
 * Implements hook_entity_property_info_alter().
 */
function bricks_molecules_entity_property_info_alter(&$info) {
  $info['brick']['properties']['machine_name']['widget'] = '_bricks_molecules_machine_name_widget';
}

/**
 * Helper function: provides a widget for a machine name property.
 */
function _bricks_molecules_machine_name_widget($entity) {
  if ($entity->type != 'unit') return;
  return array(
    '#type' => 'textfield',
    '#title' => 'Machine name',
    '#default_value' => $entity->machine_name,
  );
}
