<?php

/**
 * Implements hook_theme_registry_alter().
 */
function bricks_theme_registry_alter(&$theme_registry) {
  if (\Drupal::moduleHandler()->moduleExists('eck')) {
    _bricks_theme_registry_alter_eck($theme_registry, 'bricks', 'brick');
  }
}

/**
 * Helper function for hook_theme_registry_alter().
 *
 * Since we have to alter $theme_registry to ship templates in module - let's
 * give them better names: `brick.html.twig` over `eck-entity--brick.html.twig`.
 */
function _bricks_theme_registry_alter_eck(&$theme_registry, $module, $type, $bundle = NULL) {
  $key = 'eck_entity__' . $type;
  $template = $type;

  if (isset($bundle)) {
    $key .= '__' . $bundle;
    $template .= '--' . $bundle;
  }

  $theme_registry[$key] = array(
    'theme path' => drupal_get_path('module', $module),
    'template' => $template,
    'path' => drupal_get_path('module', $module) . '/templates',
  ) + $theme_registry['eck_entity'];
}
