<?php

/**
 * Preprocesses variables for entity.tpl.php.
 */
function bricks_organisms_preprocess_entity(&$vars) {
  $element = &$vars['elements'];
  if ($element['#entity_type'] == 'brick') {
    if ($element['#bundle'] == 'molecule' && isset($vars['content']['field_content'])) {
      $vars['content']['bricks'] = _bricks_molecular_items($element['field_content'], $vars['content']['field_content']);
      unset($vars['content']['field_content']);
    }
  }
}
