<?php

/**
 * Processes variables for theme_field().
 */
function atoms_molecules_process_field(&$vars) {
  $element = &$vars['element'];
  if ($element['#field_name'] == 'field_content') {
    $vars['items'] = _atoms_molecular_items($element, $vars['items']);
  }
}

/**
 * Preprocesses variables for entity.tpl.php.
 */
function atoms_molecules_preprocess_entity(&$vars) {
  $element = &$vars['elements'];
  if ($element['#entity_type'] == 'atom') {
    if ($element['#bundle'] == 'unit') {
      $vars['theme_hook_suggestions'][] = 'atom__unit__' . $element['#entity']->machine_name;
      if ($element['#view_mode'] == 'teaser') {
        $vars['title'] = htmlspecialchars('<' . $element['#entity']->machine_name . '>');
      }
    }
    if (isset($vars['content']['atoms'])) {
      foreach ($vars['content']['atoms'] as &$atom) {
        $atom['#base_heading_level'] = $element['#heading_level'];
      }
    }
  }
}
