<?php

/**
 * Preprocesses variables for entity.tpl.php.
 */
function atoms_organisms_preprocess_entity(&$vars) {
  $element = &$vars['elements'];
  if ($element['#entity_type'] == 'atom') {
    if ($element['#bundle'] == 'organism' && isset($vars['content']['field_content'])) {
      $vars['content']['atoms'] = _atoms_molecular_items($element['field_content'], $vars['content']['field_content']);
      unset($vars['content']['field_content']);
    }
  }
}
