name: Mirror Branch
on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: {} # Allows manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destination
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync branch
        run: |
          git remote add external https://git.drupalcode.org/project/bricks.git
          git fetch external 2.x
          git push origin external/2.x:refs/heads/2.x --force
